#!/bin/sh

USQCDDIST=$HOME/Local/packages/macosx-20130110
utils/setup-nc 2
./configure \
   --prefix=$HOME/Local/packages/clover-working \
   --target=cee-64 \
   --with-qdp=$USQCDDIST/qdp \
   --with-qmp=$USQCDDIST/qmp \
   --with-gsl=$USQCDDIST/gsl
